//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyDealer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseDetail
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Location { get; set; }
    }
}
